export enum EnvVariables {
	NODE_ENV = 'NODE_ENV',

	PORT = 'PORT',

	APP_PREFIX = 'APP_PREFIX',
	APP_PORT = 'APP_PORT',
	APP_HOST = 'APP_HOST',

	DATABASE_HOST = 'DATABASE_HOST',
	DATABASE_NAME = 'DATABASE_NAME',

	JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
	JWT_ACCESS_EXPIRES_IN = 'JWT_ACCESS_EXPIRES_IN',
	JWT_FORGOT_PASSWORD_EXPIRES_IN = 'JWT_FORGOT_PASSWORD_EXPIRES_IN',

	BCRYPT_SALT_ROUNDS = 'BCRYPT_SALT_ROUNDS',

	OPENAI_KEY = 'OPENAI_KEY',
}
